# Generated by Django 3.0.7 on 2020-06-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.TextField()),
                ('concelho', models.TextField()),
                ('freguesia', models.TextField(null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(choices=[('OLX', 'Olx'), ('IMOVIRTUAL', 'Imovirtual'), ('CUSTO_JUSTO', 'Custo Justo')])),
                ('url', models.URLField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('for_sale', models.BooleanField()),
                ('cover_photo', models.ImageField(upload_to='cover_photos')),
                ('tipologia', models.TextField(choices=[('APARTAMENTO', 'Apartamento'), ('MORADIA', 'Moradia')])),
                ('bedrooms', models.PositiveIntegerField(null=True)),
                ('bathrooms', models.PositiveIntegerField(null=True)),
                ('posted_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Location')),
            ],
            options={
                'db_table': 'ads',
            },
        ),
    ]
